### PR TITLE
Add support for systemd-cryptenroll JSON format

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by aplanas** [comment]
@lcp @okirch can we start the review process?

I am currently extending the code to predict pcr12 and will sit on top of this set of changes.

**Comment by lcp** [comment]
okirch is the only maintainer of pcr-oracle. Let's wait for his review.

**Comment by aplanas** [comment]
@okirch @lcp maybe we can move the repo to the [openSUSE](https://github.com/openSUSE) project and share the burden of review / merge

**Comment by aplanas** [comment]
The last commit predict the PCR 12 value, reading the boot loader entries and sorting them.

**Review by okirch — APPROVED** [review]

**Review by okirch — APPROVED** [review]

**Comment by okirch** [comment]
Hi Alberto, I merged your changes now. Sorry for the delay, it seems that I had failed to enable notifications so I did not see your PR; I only saw one notification about a message from you during the weekend. Sorry about this

One minor request: could you update the manpage to describe the new --policy-format parameter, please?

**Comment by aplanas** [comment]
> could you update the manpage to describe the new --policy-format parameter, please?
Yes. I will prepare a PR

**Pull request merged**
