### PR TITLE
Allow RSA key generation in more commands

### PR DESCRIPTION
**Pull request by aplanas**
The "--rsa-generate-key" now works in the "store-public-key" and "sign" commands.

### CODE REVIEW

**Comment by okirch** [comment]
Okay, I have two comments on this patch.
 a) what is the use case for --generate-rsa-key --store-public-key?
     In this case, we're left with the public key portion but the private key is lost
 b) Instead of duplicating the code, I'd rather see the if (opt_rsa_generate_key) once and inside that a check for compatible actions.

**Comment by aplanas** [comment]
> Okay, I have two comments on this patch.

Sure!

> a) what is the use case for --generate-rsa-key --store-public-key?

The situation is when I want to generate the public / private key (generate the RSA key) and store the public part. As not the first can only be done with the creation of the authorization policy (something that I do not need when I am creating the systemd files)

So with this I can generate both at the same time, avoiding the openssl call:
```
pcr-oracle --generate-rsa-key --private-key=private.pem --public-key=public store-public-key
```

> b) Instead of duplicating the code, I'd rather see the if (opt_rsa_generate_key) once and inside that a check for compatible actions.

On it.

**Comment by aplanas** [comment]
> > b) Instead of duplicating the code, I'd rather see the if (opt_rsa_generate_key) once and inside that a check for compatible actions.
> 
> On it.

Done.

**Comment by okirch** [comment]
Looks good to me now, thank you

**Pull request merged**
